version: '3'

services:
  hyperf:
    image: hyperf/hyperf:7.4-alpine-v3.11-swoole
    ports:
      - "9602:9602"
      - "9604:9604"
    volumes:
      - ./hyperf/:/opt/www/
      - ./.env:/opt/www/.env
    privileged: true
    working_dir: /opt/www/
    restart: always
    container_name: hyperf
    depends_on:
      - mysql
    networks:
      - default
    command:
      - /bin/sh
      - -c
      - |
        composer install
        php bin/hyperf.php tryCreateDatabaseAndSeeder:true
        php bin/hyperf.php start

  broker:
    image: emqx/emqx:v3.2.8
    ports:
      - 1883:1883
      - 8081:8081
      - 8083:8083
      - 8883:8883
      - 8084:8084
      - 18083:18083
    container_name: broker
    volumes:
      - ./broker/emqx_web_hook.conf:/opt/emqx/etc/plugins/emqx_web_hook.conf

  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis_a1206
    ports:
      - "${REDIS_HOST_PORT}:6379"
    volumes:
      - ${REDIS_CONF_FILE}:/etc/redis.conf:ro
      - ./redis:/data/:rw
    restart: always
    entrypoint: ["redis-server", "/etc/redis.conf"]
    environment:
      TZ: "$TZ"
    networks:
      - default

  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
      - ./mysql/data:/var/lib/mysql/:rw
    restart: always
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      TZ: "$TZ"
 # 管理后台接口
  http-api:
    image: golang:1.16.3-alpine3.13
    ports:
      - "3000:3000"
    volumes:
      - ./http-api:/opt/www/
    privileged: true
    depends_on:
      - mysql
    working_dir: /opt/www/
    restart: always
    environment:
      - GO111MODULE=on
      # 国内代理
      - GOPROXY=https://goproxy.cn,direct
    container_name: http-api
    command:
      - /bin/sh
      - -c
      - |
        go run main.go
networks:
  default:
