version: '3'

services:
        #  mqtt:
        #    image: hyperf/hyperf:7.4-alpine-v3.11-swoole
        #    ports:
        #      - "9603:9603"
        #    volumes:
        #      - ./mqtt/:/opt/www/
        #      - ./.env/:/opt/www/.env
        #    privileged: true
        #    working_dir: /opt/www/
        #    restart: always
        #    container_name: mqtt
        #    depends_on:
        #      - mysql
        #    networks:
        #      - default
        #    command:
        #      - /bin/sh
        #      - -c
        #      - |
        #        composer install
        #        php bin/simps.php mqtt:start
        #
        #  websocket:
        #    image: hyperf/hyperf:7.4-alpine-v3.11-swoole
        #    ports:
        #      - "9602:9602"
        #    volumes:
        #      - ./mqtt/:/opt/www/
        #      - ./.env/:/opt/www/.env
        #    privileged: true
        #    working_dir: /opt/www/
        #    restart: always
        #    container_name: websocket
        #    depends_on:
        #      - mysql
        #      - mqtt
        #    networks:
        #      - default
        #    command:
        #      - /bin/sh
        #      - -c
        #      - |
        #        composer install
        #        php bin/simps.php ws:start
        #

  broker:
    image: emqx/emqx
    ports:
      - 1883:1883
      - 8081:8081
      - 8083:8083
      - 8883:8883
      - 8084:8084
      - 18083:18083
    container_name: broker
    volumes:
      - "./broker/emqx_web_hook.conf:/opt/emqx/etc/plugins/emqx_web_hook.conf"

  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis
      - ./redis:/data/:rw
    ports:
      - "${REDIS_HOST_PORT}:6379"
    volumes:
      - ${REDIS_CONF_FILE}:/etc/redis.conf:ro
    restart: always
    entrypoint: ["redis-server", "/etc/redis.conf"]
    environment:
      TZ: "$TZ"
    networks:
      - default

  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
      - ./mysql/data:/var/lib/mysql/:rw
    restart: always
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      TZ: "$TZ"
networks:
  default:
