<?php
/**
 * 播放模式验证
 * @package App\Validations\WsValidations
 * @author wuchuheng  <wuchuheng@163.com>
 */
declare(strict_types=1);

namespace App\Validations\WsValidations;

use App\Events\WebsocketEvents\BaseEvent;

class PlayModeValidation extends BaseValidation
{
    public function goCheck(BaseEvent $event): void
    {
        parent::goCheck($event); // TODO: Change the autogenerated stub
    }
}